# fly.toml app configuration file generated for whatsbot-uksosq on 2026-05-14T21:01:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsbot-uksosq'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'auth_info_multi'
  destination = '/app/auth_info_multi'

[http_service]
  internal_port = 8080
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
