app = "whatsapp-ai-bot"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  # Add any environment variables here
  # For example:
  # BOT_NUMBER = "your-number@s.whatsapp.net"
  # OWNER_NUMBER = "your-number@s.whatsapp.net"

[http_service]
  internal_port = 3000
  force_https = true
  [[http_service.ports]]
    port = 80
    handlers = ["http"]
  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

[[mounts]]
  source = "auth_info_multi"
  destination = "/app/auth_info_multi"

[[mounts]]
  source = "users_json"
  destination = "/app/users.json"

[[mounts]]
  source = "_env"
  destination = "/app/.env"